version: '3.8'

services:
  inventarioDB:
    image: rodrigo1706/mysql:withdatabase
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root

  actualizar:
    command:
      - docker commit ed24e5c0079c
      - docker push rodrigo1706/mysql:withdatabase